trigger:
- master

jobs:
- job: for_Windows
  pool:
    vmImage: 'windows-latest'
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  # Archive Files
  # Compress files into .7z, .tar.gz, or .zip.
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'windows\QMK Toolbox\bin\Release\qmk_toolbox.exe'
      #includeRootFolder: true
      #archiveType: 'zip' # Options: zip, 7z, tar, wim
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/qmk_toolbox_windows_$(Build.BuildId).zip'
      #replaceExistingArchive: true
      #verbose: # Optional
      #quiet: # Optional

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: qmk_toolbox_windows

- job: for_macOS
  pool:
    vmImage: 'macOS-10.14'
  variables:
    sdk: 'macosx10.14'
    configuration: 'Release'

  steps:
  - task: Xcode@5
    inputs:
      actions: 'clean build'
      sdk: '$(sdk)'
      configuration: '$(configuration)'
      xcWorkspacePath: 'osx/QMK Toolbox.xcodeproj'
      xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
      packageApp: false

  # Archive Files
  # Compress files into .7z, .tar.gz, or .zip.
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'osx/build/Release/QMK Toolbox.app'
      includeRootFolder: true
      #archiveType: 'zip' # Options: zip, 7z, tar, wim
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/qmk_toolbox_osx_$(Build.BuildId).zip'
      #replaceExistingArchive: true
      #verbose: # Optional
      #quiet: # Optional

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: qmk_toolbox_macos

- job: release
  dependsOn: ['for_Windows', 'for_macOS']

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'qmk_toolbox_windows'
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'qmk_toolbox_macos'
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  # GitHub Release
  # Create, edit, or delete a GitHub release.
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'forRelease'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create' # Options: create, edit, delete
      target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
      tagSource: 'manual' # Required when action == Create# Options: auto, manual
      tag: $(Build.BuildNumber) # Required when action == Edit || Action == Delete || TagSource == Manual
      #title: # Optional
      #releaseNotesSource: 'file' # Optional. Options: file, input
      #releaseNotesFile: # Optional
      #releaseNotes: # Optional
      assets: '$(Build.ArtifactStagingDirectory)/**' # Optional
      #assetUploadMode: 'delete' # Optional. Options: delete, replace
      #isDraft: false # Optional
      isPreRelease: true # Optional
      #addChangeLog: true # Optional
